services:
  stream:
    container_name: fousekistream
    image: registry.panos.pet/fousekistream:latest
    environment:
      PORT: 8088
      FILENAME: /root/fousekis_all.mp3
    ports:
    - "8088:8088"
    volumes:
    - ./fousekis_all.mp3:/root/fousekis_all.mp3
    restart: unless-stopped